# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  AWS_REGION: "ap-southeast-2"
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone the repository
      uses: actions/checkout@v4
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
          role-to-assume: arn:aws:iam::148816906472:role/GithubPermissions-GithubActionsRoleF5CC769F-qPB55ib8A87Q
          role-session-name: github-actions
          aws-region: ${{ env.AWS_REGION }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 24
    - name: Install CDK
      run: npm install -g aws-cdk
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test (with coverage)
      run: |
        # Run tests and collect code coverage (XPlat collector produces cobertura xml)
        dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" -r TestResults

    - name: Install ReportGenerator
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool 
        echo "Adding dotnet tools to PATH"
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Generate HTML coverage report
      run: |
        reportgenerator -reports:"TestResults/**/coverage.cobertura.xml" -targetdir:"TestResults/CoverageReport" -reporttypes:Html

    - name: Upload coverage HTML
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html
        path: TestResults/CoverageReport
    - name: Deploy
      run:  cdk deploy AccountProcessingInfraStack --require-approval never

