# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  AWS_REGION: "ap-southeast-2"
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone the repository
      uses: actions/checkout@v4
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
          role-to-assume: arn:aws:iam::148816906472:role/GitHubPermissions-CustomAWSCDKOpenIdConnectProvider-e9cauNisMvSd
          role-session-name: github-actions
          aws-region: ${{ env.AWS_REGION }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

